#:schema https://yazi-rs.github.io/schemas/keymap.json

# Open a shell in the current Yazi directory with '!'.
# The same key works on Linux and Windows.

[[mgr.prepend_keymap]]
on = "!"
for = "unix"
run = 'shell "$SHELL" --block'
desc = "Open shell here"

[[mgr.prepend_keymap]]
on = "!"
for = "windows"
run = 'shell "pwsh.exe" --block'
desc = "Open PowerShell here"

[[mgr.prepend_keymap]]
on   = [ "<C-k>", "<C-o>" ]
# run  = 'shell "wezterm cli spawn --cwd \"%CD%\" -- nvim ." --orphan'
run  = 'shell "wezterm cli spawn -- nvim --cmd \"cd %CD%\" \"%CD%\"" --orphan'
desc = "Neovim w nowym oknie WezTerm"

[[mgr.prepend_keymap]]
on   = [ "<C-k>", "o" ]
# run  = 'shell "wezterm cli spawn --cwd \"%CD%\" -- nvim %s" --orphan'
run  = 'shell "wezterm cli spawn -- nvim --cmd \"cd %CD%\" %s" --orphan'
desc = "Neovim w nowym tabie WezTerm"

[[mgr.prepend_keymap]]
on   = [ "<C-k>", "e" ]
run  = 'shell "nvim ." --block'
desc = "Neovim na tym folderze, w aktualnym tabie"

# smart-enter.yazi: Enter wchodzi do katalogu albo otwiera plik
[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = "plugin smart-enter"
desc = "Wejdź do katalogu albo otwórz plik"

# compress.yazi
[[mgr.prepend_keymap]]
on   = [ "c", "a", "a" ]
run  = "plugin compress"
desc = "Spakuj zaznaczone"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "p" ]
run  = "plugin compress -p"
desc = "Spakuj zaznaczone (hasło)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "h" ]
run  = "plugin compress -ph"
desc = "Spakuj zaznaczone (hasło + ukryte nazwy)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "l" ]
run  = "plugin compress -l"
desc = "Spakuj zaznaczone (poziom kompresji)"

[[mgr.prepend_keymap]]
on   = [ "c", "a", "u" ]
run  = "plugin compress -phl"
desc = "Spakuj zaznaczone (hasło + nazwy + poziom)"
