#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 5

// Włącza Kinetic Mouse Keys
#define MK_KINETIC_SPEED

// Domyślne wartości Kinetic Mode
//#define MOUSEKEY_DELAY 5
//#define MOUSEKEY_DELAY 3
#define MOUSEKEY_DELAY 2

#define MOUSEKEY_INTERVAL 10
#define MOUSEKEY_MOVE_DELTA 16

//#define MOUSEKEY_INITIAL_SPEED 70
//#define MOUSEKEY_INITIAL_SPEED 150
//#define MOUSEKEY_INITIAL_SPEED 450
#define MOUSEKEY_INITIAL_SPEED 350

#define MOUSEKEY_BASE_SPEED 4500
#define MOUSEKEY_DECELERATED_SPEED 250
#define MOUSEKEY_ACCELERATED_SPEED 5500

// Domyślne wartości Kinetic Mode dla scrolla
#define MOUSEKEY_WHEEL_INITIAL_MOVEMENTS 16
#define MOUSEKEY_WHEEL_BASE_MOVEMENTS 32
#define MOUSEKEY_WHEEL_ACCELERATED_MOVEMENTS 48
#define MOUSEKEY_WHEEL_DECELERATED_MOVEMENTS 8

