#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 5

// // Włącza Combined Mouse Keys #define MK_COMBINED
//
// #define MOUSEKEY_DELAY 80
// #define MOUSEKEY_INTERVAL 16
// #define MOUSEKEY_MOVE_DELTA 4
// #define MOUSEKEY_MAX_SPEED 16
// #define MOUSEKEY_TIME_TO_MAX 40
//
// #define MOUSEKEY_WHEEL_DELAY 80
// #define MOUSEKEY_WHEEL_INTERVAL 80
// #define MOUSEKEY_WHEEL_DELTA 1
// #define MOUSEKEY_WHEEL_MAX_SPEED 4
// #define MOUSEKEY_WHEEL_TIME_TO_MAX 40

#define MK_KINETIC_SPEED

#define MOUSEKEY_DELAY 2
#define MOUSEKEY_INTERVAL 8
#define MOUSEKEY_MOVE_DELTA 20

#define MOUSEKEY_INITIAL_SPEED 250
#define MOUSEKEY_BASE_SPEED 6500
#define MOUSEKEY_DECELERATED_SPEED 180
#define MOUSEKEY_ACCELERATED_SPEED 9000

#define MOUSEKEY_WHEEL_INITIAL_MOVEMENTS 8
#define MOUSEKEY_WHEEL_BASE_MOVEMENTS 32
#define MOUSEKEY_WHEEL_ACCELERATED_MOVEMENTS 64
#define MOUSEKEY_WHEEL_DECELERATED_MOVEMENTS 4

#define MOUSEKEY_OVERLAP_RESET

