local set = vim.opt

set.timeout = true
set.timeoutlen = 200
set.hidden = true
set.swapfile = false
set.backup = false
set.writebackup = false
set.incsearch = true
set.signcolumn = "yes"
set.wildmenu = true
set.scrolloff = 8
set.wrap = false
set.history = 1000
set.clipboard = "unnamedplus"
set.cindent = true
set.autoindent = true
set.smartindent = true
set.smarttab = true
set.expandtab = true
set.softtabstop = 4
set.shiftwidth = 4
set.tabstop = 4
set.encoding = "utf-8"
set.termguicolors = true
set.hlsearch = true
set.cmdheight = 2
set.relativenumber = true
set.cursorline = true
set.showmode = true
set.ignorecase = true
set.smartcase = true
set.completeopt = { "menuone", "noselect" }
set.mouse = "a"
set.guicursor = "i-ci:ver20, c-n-v-sm:block"

